version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgresdb
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5435:5432"
    networks:
      - shared_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "15434:80"
    networks:
      - shared_network
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  api:
    build:
      context: . 
    container_name: emprestimo-api
    ports:
      - "8085:8085"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - shared_network
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      APP_NAME: ${APP_NAME}
      SERVER_PORT: ${SERVER_PORT}
    restart: unless-stopped

networks:
  shared_network:
    external: true

volumes:
  postgres_data:
  pgadmin_data:
